spring.application.name=gateway

# Kafka
spring.kafka.bootstrap-servers=192.168.18.192:9092
kafka.topic.market-quote=market-quote

# SCB WebSocket
scb.websocket.uri=ws://localhost:3000/scale/v1/ws-service/quotes/XYZ/RateCatA
scb.websocket.reconnect.initial-delay-ms=1000
scb.websocket.reconnect.max-delay-ms=30000

# SCB Subscription HTTP
scb.subscription.url=http://localhost:3000/scale/v1/stream-service/subscribe/{clientId}/{rateCatId}
scb.unsubscription.url=http://localhost:3000/scale/v1/stream-service/unsubscribe/{clientId}/{rateCatId}
scb.client-id=XYZ
scb.rate-category-id=RateCatA

# Disruptor
disruptor.ring-buffer-size=65536

# Kafka Batch Publishing
kafka.batch.max-size=25000
kafka.batch.flush-interval-ms=50
kafka.batch.worker-count=4
kafka.batch.queue-capacity=262144
